DEBUG = True

DEBUG_LEVELS = True
DEBUG_LEVEL_CHANGE_SHORTCUTS = True
DEBUG_LEVEL_CHANGE_WITHOUT_COINS_COLLECTING = True

DEBUG_TILES_VISUAL_COLLISION = True
DEBUG_TILES_VISUAL_TRIGGER = True


if not DEBUG:
    DEBUG_LEVELS = False
    DEBUG_LEVEL_CHANGE_SHORTCUTS = False
    DEBUG_LEVEL_CHANGE_WITHOUT_COINS_COLLECTING = False

    DEBUG_TILES_VISUAL_COLLISION = False
    DEBUG_TILES_VISUAL_TRIGGER = False
