import pygame as pg

from src.game.PlayerKeymap import PlayerKeymap

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
TARGET_FPS = 60
TITLE = "ECTS catchers"

PLAYER_LEFT_KEYMAP = PlayerKeymap()
PLAYER_LEFT_KEYMAP.MOVE_UP = pg.K_w
PLAYER_LEFT_KEYMAP.MOVE_RIGHT = pg.K_d
PLAYER_LEFT_KEYMAP.MOVE_DOWN = pg.K_s
PLAYER_LEFT_KEYMAP.MOVE_LEFT = pg.K_a

PLAYER_RIGHT_KEYMAP = PlayerKeymap()
PLAYER_RIGHT_KEYMAP.MOVE_UP = pg.K_UP
PLAYER_RIGHT_KEYMAP.MOVE_RIGHT = pg.K_RIGHT
PLAYER_RIGHT_KEYMAP.MOVE_DOWN = pg.K_DOWN
PLAYER_RIGHT_KEYMAP.MOVE_LEFT = pg.K_LEFT
